title: my awesome test
author: MCs
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  no loitering around - nothing to see here
# social links
twitter_username: McSvenster
github_username:  McSvenster

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
